#!/bin/bash

# AI-Powered Git Helper Script
# Simplifies common git operations with intelligent automation

set -e

PROJECT_DIR="/home/user/webapp"
cd "$PROJECT_DIR"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function: Smart commit with AI-generated message
ai_commit() {
    echo -e "${BLUE}🤖 AI Smart Commit${NC}"
    
    # Check for changes
    if [[ -z $(git status -s) ]]; then
        echo -e "${YELLOW}No changes to commit${NC}"
        return
    fi
    
    # Show what's changed
    echo -e "${GREEN}Changes detected:${NC}"
    git status -s
    
    # Generate smart commit message based on changes
    CHANGED_FILES=$(git status -s | wc -l)
    MAIN_FILE=$(git status -s | head -1 | awk '{print $2}')
    
    read -p "Enter commit message (or press Enter for auto-generated): " COMMIT_MSG
    
    if [[ -z "$COMMIT_MSG" ]]; then
        COMMIT_MSG="chore: update $CHANGED_FILES file(s) - $(date +'%Y-%m-%d %H:%M')"
    fi
    
    git add .
    git commit -m "$COMMIT_MSG"
    echo -e "${GREEN}✅ Committed successfully!${NC}"
}

# Function: Smart sync with remote (handles conflicts)
ai_sync() {
    echo -e "${BLUE}🔄 AI Smart Sync${NC}"
    
    # Get current branch
    CURRENT_BRANCH=$(git branch --show-current)
    echo -e "Current branch: ${GREEN}$CURRENT_BRANCH${NC}"
    
    # Fetch latest changes
    echo -e "${YELLOW}Fetching latest changes...${NC}"
    git fetch origin
    
    # Check if there are conflicts
    git merge origin/main --no-commit --no-ff 2>&1 | tee /tmp/merge_output.txt || true
    
    if grep -q "CONFLICT" /tmp/merge_output.txt; then
        echo -e "${RED}⚠️  Conflicts detected!${NC}"
        echo -e "${YELLOW}Conflicted files:${NC}"
        git diff --name-only --diff-filter=U
        
        echo -e "\n${BLUE}AI Conflict Resolution Options:${NC}"
        echo "1. Accept remote changes (theirs)"
        echo "2. Keep local changes (ours)"
        echo "3. Manual resolution (open files)"
        read -p "Choose option (1-3): " RESOLVE_OPTION
        
        case $RESOLVE_OPTION in
            1)
                git checkout --theirs .
                git add .
                echo -e "${GREEN}✅ Accepted remote changes${NC}"
                ;;
            2)
                git checkout --ours .
                git add .
                echo -e "${GREEN}✅ Kept local changes${NC}"
                ;;
            3)
                echo -e "${YELLOW}Please resolve conflicts manually and run: git add . && git commit${NC}"
                return
                ;;
        esac
        
        git commit -m "chore: resolve merge conflicts - $(date +'%Y-%m-%d %H:%M')"
    else
        git merge origin/main
        echo -e "${GREEN}✅ Synced successfully!${NC}"
    fi
}

# Function: Create PR with AI-generated description
ai_pr() {
    echo -e "${BLUE}📝 AI Pull Request Creator${NC}"
    
    # Ensure changes are committed
    if [[ ! -z $(git status -s) ]]; then
        echo -e "${YELLOW}Uncommitted changes detected. Committing first...${NC}"
        ai_commit
    fi
    
    # Push current branch
    CURRENT_BRANCH=$(git branch --show-current)
    echo -e "${YELLOW}Pushing branch: $CURRENT_BRANCH${NC}"
    git push -u origin "$CURRENT_BRANCH" --force-with-lease
    
    # Get commit messages for PR description
    COMMITS=$(git log origin/main..HEAD --pretty=format:"- %s" | head -10)
    
    read -p "PR Title: " PR_TITLE
    if [[ -z "$PR_TITLE" ]]; then
        PR_TITLE="Update: $CURRENT_BRANCH - $(date +'%Y-%m-%d')"
    fi
    
    # Generate PR description
    PR_BODY="## Changes

$COMMITS

## Testing
- [ ] Tested locally
- [ ] All tests passing
- [ ] No TypeScript errors

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

---
*Generated by AI Git Helper - $(date)*"
    
    # Create PR (requires GitHub CLI)
    if command -v gh &> /dev/null; then
        echo "$PR_BODY" | gh pr create --title "$PR_TITLE" --body-file - --base main --head "$CURRENT_BRANCH"
        echo -e "${GREEN}✅ Pull Request created!${NC}"
        gh pr view --web
    else
        echo -e "${YELLOW}GitHub CLI not installed. Install with: brew install gh${NC}"
        echo -e "${BLUE}PR Details saved to pr-description.md${NC}"
        echo -e "Title: $PR_TITLE\n\n$PR_BODY" > pr-description.md
    fi
}

# Function: Quick status check
ai_status() {
    echo -e "${BLUE}📊 AI Status Check${NC}\n"
    
    echo -e "${GREEN}Current Branch:${NC}"
    git branch --show-current
    
    echo -e "\n${GREEN}Recent Commits:${NC}"
    git log --oneline -5
    
    echo -e "\n${GREEN}Uncommitted Changes:${NC}"
    git status -s
    
    echo -e "\n${GREEN}Branch Status:${NC}"
    git fetch origin &>/dev/null
    AHEAD=$(git rev-list --count origin/main..HEAD 2>/dev/null || echo "0")
    BEHIND=$(git rev-list --count HEAD..origin/main 2>/dev/null || echo "0")
    echo "Ahead: $AHEAD commits | Behind: $BEHIND commits"
}

# Function: AI code review
ai_review() {
    echo -e "${BLUE}🔍 AI Code Review${NC}\n"
    
    echo -e "${GREEN}Files changed since last commit:${NC}"
    git diff --stat
    
    echo -e "\n${GREEN}Detailed changes:${NC}"
    git diff --color | head -100
    
    echo -e "\n${YELLOW}💡 Running TypeScript check...${NC}"
    npm run check 2>&1 | head -20 || echo "No type errors found!"
}

# Function: Show menu
show_menu() {
    echo -e "\n${BLUE}╔════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║   AI Git Helper - Main Menu       ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════╝${NC}\n"
    
    echo "1. 🤖 Smart Commit (AI-powered)"
    echo "2. 🔄 Smart Sync (handle conflicts)"
    echo "3. 📝 Create Pull Request"
    echo "4. 📊 Status Check"
    echo "5. 🔍 Code Review"
    echo "6. 🚀 Full Workflow (commit + sync + PR)"
    echo "7. ❌ Exit"
    echo
}

# Function: Full workflow
ai_full_workflow() {
    echo -e "${BLUE}🚀 Running Full AI Workflow${NC}\n"
    
    ai_status
    echo -e "\n${YELLOW}Step 1: Committing changes...${NC}"
    ai_commit
    
    echo -e "\n${YELLOW}Step 2: Syncing with remote...${NC}"
    ai_sync
    
    echo -e "\n${YELLOW}Step 3: Creating PR...${NC}"
    ai_pr
    
    echo -e "\n${GREEN}✅ Full workflow complete!${NC}"
}

# Main menu loop
main() {
    if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
        echo "AI Git Helper - Simplify your Git workflow"
        echo ""
        echo "Usage: $0 [command]"
        echo ""
        echo "Commands:"
        echo "  commit   - Smart commit with AI message"
        echo "  sync     - Sync with remote (handles conflicts)"
        echo "  pr       - Create pull request"
        echo "  status   - Show status"
        echo "  review   - Code review"
        echo "  workflow - Run full workflow"
        echo ""
        echo "Run without arguments for interactive mode"
        exit 0
    fi
    
    # Direct command execution
    case "$1" in
        commit)
            ai_commit
            exit 0
            ;;
        sync)
            ai_sync
            exit 0
            ;;
        pr)
            ai_pr
            exit 0
            ;;
        status)
            ai_status
            exit 0
            ;;
        review)
            ai_review
            exit 0
            ;;
        workflow)
            ai_full_workflow
            exit 0
            ;;
    esac
    
    # Interactive mode
    while true; do
        show_menu
        read -p "Choose option (1-7): " choice
        
        case $choice in
            1) ai_commit ;;
            2) ai_sync ;;
            3) ai_pr ;;
            4) ai_status ;;
            5) ai_review ;;
            6) ai_full_workflow ;;
            7) 
                echo -e "${GREEN}Goodbye! 👋${NC}"
                exit 0
                ;;
            *)
                echo -e "${RED}Invalid option${NC}"
                ;;
        esac
    done
}

main "$@"
